services:
  carservicewebapi:
    build:
        context: .
        dockerfile: Dockerfile
    image: carservice/webapi:v1
    container_name: webapi
    ports:
        - "1488:8080"
    environment:
        - ASPNETCORE_ENVIROMENT=Development
        - ConnectionStrings__CarServiceDbContext="Server=host.docker.internal, 1433; User Id = sa; Password = Qwerty1488; Database=CarServiceDB; Trusted_Connection = true; TrustServerCertificate = true" 
    networks:
        - my_network



networks:
 my_network:
    driver: bridge