// <auto-generated />
using System;
using CarService.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarService.DataAccess.Migrations
{
    [DbContext(typeof(CarServiceDbContext))]
    partial class CarServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarService.DataAccess.Entities.AutoPartEntity", b =>
                {
                    b.Property<Guid>("AutoPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AutoPartName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("PartNumber")
                        .HasMaxLength(6)
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("StockAmount")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AutoPartId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("AutoParts");
                });

            modelBuilder.Entity("CarService.DataAccess.Entities.ClientEntity", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CarService.DataAccess.Entities.CorporateAccountEntity", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LogIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccountId");

                    b.HasIndex("WarehouseId")
                        .IsUnique();

                    b.ToTable("CorporateAccounts");
                });

            modelBuilder.Entity("CarService.DataAccess.Entities.ManufacturerEntity", b =>
                {
                    b.Property<Guid>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("CarService.DataAccess.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OrderStatus")
                        .HasColumnType("bit");

                    b.HasKey("OrderId");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CarService.DataAccess.Entities.OrderPartEntity", b =>
                {
                    b.Property<Guid>("OrderedPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ArrivalWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AutoPartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartureWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderedPartId");

                    b.HasIndex("ArrivalWarehouseId")
                        .IsUnique()
                        .HasFilter("[ArrivalWarehouseId] IS NOT NULL");

                    b.HasIndex("AutoPartId")
                        .IsUnique();

                    b.HasIndex("DepartureWarehouseId")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("OrderParts");
                });

            modelBuilder.Entity("CarService.DataAccess.Entities.OrganizationEntity", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TIN")
                        .HasMaxLength(10)
                        .HasColumnType("bigint");

                    b.Property<string>("TitleOrganization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganizationId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("CarService.DataAccess.Entities.WarehouseEntity", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WarehouseId");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("CarService.DataAccess.Entities.AutoPartEntity", b =>
                {
                    b.HasOne("CarService.DataAccess.Entities.ManufacturerEntity", "Manufacturer")
                        .WithMany("AutoParts")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarService.DataAccess.Entities.WarehouseEntity", "Warehouse")
                        .WithMany("AutoParts")
                        .HasForeignKey("WarehouseId");

                    b.Navigation("Manufacturer");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("CarService.DataAccess.Entities.ClientEntity", b =>
                {
                    b.HasOne("CarService.DataAccess.Entities.OrganizationEntity", "Organization")
                        .WithMany("Clients")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CarService.DataAccess.Entities.CorporateAccountEntity", b =>
                {
                    b.HasOne("CarService.DataAccess.Entities.WarehouseEntity", "Warehouse")
                        .WithOne()
                        .HasForeignKey("CarService.DataAccess.Entities.CorporateAccountEntity", "WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("CarService.DataAccess.Entities.OrderEntity", b =>
                {
                    b.HasOne("CarService.DataAccess.Entities.ClientEntity", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CarService.DataAccess.Entities.OrderPartEntity", b =>
                {
                    b.HasOne("CarService.DataAccess.Entities.WarehouseEntity", "ArrivalWarehouse")
                        .WithOne()
                        .HasForeignKey("CarService.DataAccess.Entities.OrderPartEntity", "ArrivalWarehouseId");

                    b.HasOne("CarService.DataAccess.Entities.AutoPartEntity", "AutoPart")
                        .WithOne()
                        .HasForeignKey("CarService.DataAccess.Entities.OrderPartEntity", "AutoPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarService.DataAccess.Entities.WarehouseEntity", "DepartureWarehouse")
                        .WithOne()
                        .HasForeignKey("CarService.DataAccess.Entities.OrderPartEntity", "DepartureWarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarService.DataAccess.Entities.OrderEntity", "Order")
                        .WithMany("OrderParts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArrivalWarehouse");

                    b.Navigation("AutoPart");

                    b.Navigation("DepartureWarehouse");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CarService.DataAccess.Entities.ClientEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CarService.DataAccess.Entities.ManufacturerEntity", b =>
                {
                    b.Navigation("AutoParts");
                });

            modelBuilder.Entity("CarService.DataAccess.Entities.OrderEntity", b =>
                {
                    b.Navigation("OrderParts");
                });

            modelBuilder.Entity("CarService.DataAccess.Entities.OrganizationEntity", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("CarService.DataAccess.Entities.WarehouseEntity", b =>
                {
                    b.Navigation("AutoParts");
                });
#pragma warning restore 612, 618
        }
    }
}
